/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedSponsorshipsIndexRouteImport } from './routes/_authed/sponsorships/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedPaymentsIndexRouteImport } from './routes/_authed/payments/index'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders/index'
import { Route as AuthedDrugsIndexRouteImport } from './routes/_authed/drugs/index'
import { Route as AuthedContactsIndexRouteImport } from './routes/_authed/contacts/index'
import { Route as AuthedAnimalsIndexRouteImport } from './routes/_authed/animals/index'
import { Route as AuthedTreatmentsCreateRouteImport } from './routes/_authed/treatments/create'
import { Route as AuthedSponsorshipsCreateRouteImport } from './routes/_authed/sponsorships/create'
import { Route as AuthedProductsCreateRouteImport } from './routes/_authed/products/create'
import { Route as AuthedPaymentsCreateRouteImport } from './routes/_authed/payments/create'
import { Route as AuthedOrdersCreateRouteImport } from './routes/_authed/orders/create'
import { Route as AuthedFieldCalendarTillagesRouteImport } from './routes/_authed/field-calendar/tillages'
import { Route as AuthedFieldCalendarPlotsRouteImport } from './routes/_authed/field-calendar/plots'
import { Route as AuthedFieldCalendarHarvestsRouteImport } from './routes/_authed/field-calendar/harvests'
import { Route as AuthedFieldCalendarFertilizerApplicationsRouteImport } from './routes/_authed/field-calendar/fertilizer-applications'
import { Route as AuthedFieldCalendarCropRotationsRouteImport } from './routes/_authed/field-calendar/crop-rotations'
import { Route as AuthedFieldCalendarCropProtectionApplicationsRouteImport } from './routes/_authed/field-calendar/crop-protection-applications'
import { Route as AuthedDrugsCreateRouteImport } from './routes/_authed/drugs/create'
import { Route as AuthedContactsCreateRouteImport } from './routes/_authed/contacts/create'
import { Route as AuthedAnimalsTurnoutJournalRouteImport } from './routes/_authed/animals/turnout-journal'
import { Route as AuthedAnimalsTreatmentsJournalRouteImport } from './routes/_authed/animals/treatments-journal'
import { Route as AuthedAnimalsHerdsRouteImport } from './routes/_authed/animals/herds'
import { Route as AuthedAnimalsEarTagsRouteImport } from './routes/_authed/animals/ear-tags'
import { Route as AuthedAnimalsCreateRouteImport } from './routes/_authed/animals/create'
import { Route as AuthedTreatmentsTreatmentIdIndexRouteImport } from './routes/_authed/treatments/$treatmentId.index'
import { Route as AuthedSponsorshipsProgramsIndexRouteImport } from './routes/_authed/sponsorships/programs/index'
import { Route as AuthedSponsorshipsSponsorshipIdIndexRouteImport } from './routes/_authed/sponsorships/$sponsorshipId.index'
import { Route as AuthedProductsProductIdIndexRouteImport } from './routes/_authed/products/$productId.index'
import { Route as AuthedPaymentsPaymentIdIndexRouteImport } from './routes/_authed/payments/$paymentId.index'
import { Route as AuthedOrdersOrderIdIndexRouteImport } from './routes/_authed/orders/$orderId.index'
import { Route as AuthedDrugsDrugIdIndexRouteImport } from './routes/_authed/drugs/$drugId.index'
import { Route as AuthedContactsContactIdIndexRouteImport } from './routes/_authed/contacts/$contactId.index'
import { Route as AuthedAnimalsAnimalIdIndexRouteImport } from './routes/_authed/animals/$animalId.index'
import { Route as AuthedTreatmentsTreatmentIdEditRouteImport } from './routes/_authed/treatments/$treatmentId.edit'
import { Route as AuthedSponsorshipsProgramsCreateRouteImport } from './routes/_authed/sponsorships/programs/create'
import { Route as AuthedSponsorshipsSponsorshipIdEditRouteImport } from './routes/_authed/sponsorships/$sponsorshipId.edit'
import { Route as AuthedProductsProductIdEditRouteImport } from './routes/_authed/products/$productId.edit'
import { Route as AuthedPaymentsPaymentIdEditRouteImport } from './routes/_authed/payments/$paymentId.edit'
import { Route as AuthedOrdersOrderIdEditRouteImport } from './routes/_authed/orders/$orderId.edit'
import { Route as AuthedFieldCalendarTillagesCreateRouteImport } from './routes/_authed/field-calendar/tillages_.create'
import { Route as AuthedFieldCalendarTillagesTillageIdRouteImport } from './routes/_authed/field-calendar/tillages_.$tillageId'
import { Route as AuthedFieldCalendarPlotsPlotIdRouteImport } from './routes/_authed/field-calendar/plots_.$plotId'
import { Route as AuthedFieldCalendarHarvestsCreateRouteImport } from './routes/_authed/field-calendar/harvests_.create'
import { Route as AuthedFieldCalendarHarvestsHarvestIdRouteImport } from './routes/_authed/field-calendar/harvests_.$harvestId'
import { Route as AuthedFieldCalendarFertilizerApplicationsCreateRouteImport } from './routes/_authed/field-calendar/fertilizer-applications_.create'
import { Route as AuthedFieldCalendarCropRotationsCreateRouteImport } from './routes/_authed/field-calendar/crop-rotations_.create'
import { Route as AuthedFieldCalendarCropProtectionApplicationsCreateRouteImport } from './routes/_authed/field-calendar/crop-protection-applications_.create'
import { Route as AuthedDrugsDrugIdEditRouteImport } from './routes/_authed/drugs/$drugId.edit'
import { Route as AuthedContactsContactIdEditRouteImport } from './routes/_authed/contacts/$contactId.edit'
import { Route as AuthedAnimalsHerdsHerdIdRouteImport } from './routes/_authed/animals/herds_.$herdId'
import { Route as AuthedAnimalsAnimalIdEditRouteImport } from './routes/_authed/animals/$animalId.edit'
import { Route as AuthedSponsorshipsProgramsProgramIdIndexRouteImport } from './routes/_authed/sponsorships/programs/$programId.index'
import { Route as AuthedSponsorshipsProgramsProgramIdEditRouteImport } from './routes/_authed/sponsorships/programs/$programId.edit'
import { Route as AuthedFieldCalendarTillagesTillageIdEditRouteImport } from './routes/_authed/field-calendar/tillages_.$tillageId.edit'
import { Route as AuthedFieldCalendarCropRotationsRotationIdEditRouteImport } from './routes/_authed/field-calendar/crop-rotations_.$rotationId.edit'
import { Route as AuthedFieldCalendarCropProtectionApplicationsIdEditRouteImport } from './routes/_authed/field-calendar/crop-protection-applications_.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSponsorshipsIndexRoute = AuthedSponsorshipsIndexRouteImport.update({
  id: '/sponsorships/',
  path: '/sponsorships/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPaymentsIndexRoute = AuthedPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDrugsIndexRoute = AuthedDrugsIndexRouteImport.update({
  id: '/drugs/',
  path: '/drugs/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedContactsIndexRoute = AuthedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnimalsIndexRoute = AuthedAnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTreatmentsCreateRoute = AuthedTreatmentsCreateRouteImport.update({
  id: '/treatments/create',
  path: '/treatments/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSponsorshipsCreateRoute =
  AuthedSponsorshipsCreateRouteImport.update({
    id: '/sponsorships/create',
    path: '/sponsorships/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsCreateRoute = AuthedProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPaymentsCreateRoute = AuthedPaymentsCreateRouteImport.update({
  id: '/payments/create',
  path: '/payments/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersCreateRoute = AuthedOrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFieldCalendarTillagesRoute =
  AuthedFieldCalendarTillagesRouteImport.update({
    id: '/field-calendar/tillages',
    path: '/field-calendar/tillages',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarPlotsRoute =
  AuthedFieldCalendarPlotsRouteImport.update({
    id: '/field-calendar/plots',
    path: '/field-calendar/plots',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarHarvestsRoute =
  AuthedFieldCalendarHarvestsRouteImport.update({
    id: '/field-calendar/harvests',
    path: '/field-calendar/harvests',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarFertilizerApplicationsRoute =
  AuthedFieldCalendarFertilizerApplicationsRouteImport.update({
    id: '/field-calendar/fertilizer-applications',
    path: '/field-calendar/fertilizer-applications',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarCropRotationsRoute =
  AuthedFieldCalendarCropRotationsRouteImport.update({
    id: '/field-calendar/crop-rotations',
    path: '/field-calendar/crop-rotations',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarCropProtectionApplicationsRoute =
  AuthedFieldCalendarCropProtectionApplicationsRouteImport.update({
    id: '/field-calendar/crop-protection-applications',
    path: '/field-calendar/crop-protection-applications',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDrugsCreateRoute = AuthedDrugsCreateRouteImport.update({
  id: '/drugs/create',
  path: '/drugs/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedContactsCreateRoute = AuthedContactsCreateRouteImport.update({
  id: '/contacts/create',
  path: '/contacts/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnimalsTurnoutJournalRoute =
  AuthedAnimalsTurnoutJournalRouteImport.update({
    id: '/animals/turnout-journal',
    path: '/animals/turnout-journal',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsTreatmentsJournalRoute =
  AuthedAnimalsTreatmentsJournalRouteImport.update({
    id: '/animals/treatments-journal',
    path: '/animals/treatments-journal',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsHerdsRoute = AuthedAnimalsHerdsRouteImport.update({
  id: '/animals/herds',
  path: '/animals/herds',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnimalsEarTagsRoute = AuthedAnimalsEarTagsRouteImport.update({
  id: '/animals/ear-tags',
  path: '/animals/ear-tags',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnimalsCreateRoute = AuthedAnimalsCreateRouteImport.update({
  id: '/animals/create',
  path: '/animals/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTreatmentsTreatmentIdIndexRoute =
  AuthedTreatmentsTreatmentIdIndexRouteImport.update({
    id: '/treatments/$treatmentId/',
    path: '/treatments/$treatmentId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsProgramsIndexRoute =
  AuthedSponsorshipsProgramsIndexRouteImport.update({
    id: '/sponsorships/programs/',
    path: '/sponsorships/programs/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsSponsorshipIdIndexRoute =
  AuthedSponsorshipsSponsorshipIdIndexRouteImport.update({
    id: '/sponsorships/$sponsorshipId/',
    path: '/sponsorships/$sponsorshipId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsProductIdIndexRoute =
  AuthedProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedPaymentsPaymentIdIndexRoute =
  AuthedPaymentsPaymentIdIndexRouteImport.update({
    id: '/payments/$paymentId/',
    path: '/payments/$paymentId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOrdersOrderIdIndexRoute =
  AuthedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDrugsDrugIdIndexRoute = AuthedDrugsDrugIdIndexRouteImport.update({
  id: '/drugs/$drugId/',
  path: '/drugs/$drugId/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedContactsContactIdIndexRoute =
  AuthedContactsContactIdIndexRouteImport.update({
    id: '/contacts/$contactId/',
    path: '/contacts/$contactId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsAnimalIdIndexRoute =
  AuthedAnimalsAnimalIdIndexRouteImport.update({
    id: '/animals/$animalId/',
    path: '/animals/$animalId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedTreatmentsTreatmentIdEditRoute =
  AuthedTreatmentsTreatmentIdEditRouteImport.update({
    id: '/treatments/$treatmentId/edit',
    path: '/treatments/$treatmentId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsProgramsCreateRoute =
  AuthedSponsorshipsProgramsCreateRouteImport.update({
    id: '/sponsorships/programs/create',
    path: '/sponsorships/programs/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsSponsorshipIdEditRoute =
  AuthedSponsorshipsSponsorshipIdEditRouteImport.update({
    id: '/sponsorships/$sponsorshipId/edit',
    path: '/sponsorships/$sponsorshipId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsProductIdEditRoute =
  AuthedProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedPaymentsPaymentIdEditRoute =
  AuthedPaymentsPaymentIdEditRouteImport.update({
    id: '/payments/$paymentId/edit',
    path: '/payments/$paymentId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOrdersOrderIdEditRoute = AuthedOrdersOrderIdEditRouteImport.update({
  id: '/orders/$orderId/edit',
  path: '/orders/$orderId/edit',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedFieldCalendarTillagesCreateRoute =
  AuthedFieldCalendarTillagesCreateRouteImport.update({
    id: '/field-calendar/tillages_/create',
    path: '/field-calendar/tillages/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarTillagesTillageIdRoute =
  AuthedFieldCalendarTillagesTillageIdRouteImport.update({
    id: '/field-calendar/tillages_/$tillageId',
    path: '/field-calendar/tillages/$tillageId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarPlotsPlotIdRoute =
  AuthedFieldCalendarPlotsPlotIdRouteImport.update({
    id: '/field-calendar/plots_/$plotId',
    path: '/field-calendar/plots/$plotId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarHarvestsCreateRoute =
  AuthedFieldCalendarHarvestsCreateRouteImport.update({
    id: '/field-calendar/harvests_/create',
    path: '/field-calendar/harvests/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarHarvestsHarvestIdRoute =
  AuthedFieldCalendarHarvestsHarvestIdRouteImport.update({
    id: '/field-calendar/harvests_/$harvestId',
    path: '/field-calendar/harvests/$harvestId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarFertilizerApplicationsCreateRoute =
  AuthedFieldCalendarFertilizerApplicationsCreateRouteImport.update({
    id: '/field-calendar/fertilizer-applications_/create',
    path: '/field-calendar/fertilizer-applications/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarCropRotationsCreateRoute =
  AuthedFieldCalendarCropRotationsCreateRouteImport.update({
    id: '/field-calendar/crop-rotations_/create',
    path: '/field-calendar/crop-rotations/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarCropProtectionApplicationsCreateRoute =
  AuthedFieldCalendarCropProtectionApplicationsCreateRouteImport.update({
    id: '/field-calendar/crop-protection-applications_/create',
    path: '/field-calendar/crop-protection-applications/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDrugsDrugIdEditRoute = AuthedDrugsDrugIdEditRouteImport.update({
  id: '/drugs/$drugId/edit',
  path: '/drugs/$drugId/edit',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedContactsContactIdEditRoute =
  AuthedContactsContactIdEditRouteImport.update({
    id: '/contacts/$contactId/edit',
    path: '/contacts/$contactId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsHerdsHerdIdRoute =
  AuthedAnimalsHerdsHerdIdRouteImport.update({
    id: '/animals/herds_/$herdId',
    path: '/animals/herds/$herdId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsAnimalIdEditRoute =
  AuthedAnimalsAnimalIdEditRouteImport.update({
    id: '/animals/$animalId/edit',
    path: '/animals/$animalId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsProgramsProgramIdIndexRoute =
  AuthedSponsorshipsProgramsProgramIdIndexRouteImport.update({
    id: '/sponsorships/programs/$programId/',
    path: '/sponsorships/programs/$programId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsProgramsProgramIdEditRoute =
  AuthedSponsorshipsProgramsProgramIdEditRouteImport.update({
    id: '/sponsorships/programs/$programId/edit',
    path: '/sponsorships/programs/$programId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarTillagesTillageIdEditRoute =
  AuthedFieldCalendarTillagesTillageIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedFieldCalendarTillagesTillageIdRoute,
  } as any)
const AuthedFieldCalendarCropRotationsRotationIdEditRoute =
  AuthedFieldCalendarCropRotationsRotationIdEditRouteImport.update({
    id: '/field-calendar/crop-rotations_/$rotationId/edit',
    path: '/field-calendar/crop-rotations/$rotationId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedFieldCalendarCropProtectionApplicationsIdEditRoute =
  AuthedFieldCalendarCropProtectionApplicationsIdEditRouteImport.update({
    id: '/field-calendar/crop-protection-applications_/$id/edit',
    path: '/field-calendar/crop-protection-applications/$id/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthedAccountRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/animals/create': typeof AuthedAnimalsCreateRoute
  '/animals/ear-tags': typeof AuthedAnimalsEarTagsRoute
  '/animals/herds': typeof AuthedAnimalsHerdsRoute
  '/animals/treatments-journal': typeof AuthedAnimalsTreatmentsJournalRoute
  '/animals/turnout-journal': typeof AuthedAnimalsTurnoutJournalRoute
  '/contacts/create': typeof AuthedContactsCreateRoute
  '/drugs/create': typeof AuthedDrugsCreateRoute
  '/field-calendar/crop-protection-applications': typeof AuthedFieldCalendarCropProtectionApplicationsRoute
  '/field-calendar/crop-rotations': typeof AuthedFieldCalendarCropRotationsRoute
  '/field-calendar/fertilizer-applications': typeof AuthedFieldCalendarFertilizerApplicationsRoute
  '/field-calendar/harvests': typeof AuthedFieldCalendarHarvestsRoute
  '/field-calendar/plots': typeof AuthedFieldCalendarPlotsRoute
  '/field-calendar/tillages': typeof AuthedFieldCalendarTillagesRoute
  '/orders/create': typeof AuthedOrdersCreateRoute
  '/payments/create': typeof AuthedPaymentsCreateRoute
  '/products/create': typeof AuthedProductsCreateRoute
  '/sponsorships/create': typeof AuthedSponsorshipsCreateRoute
  '/treatments/create': typeof AuthedTreatmentsCreateRoute
  '/animals/': typeof AuthedAnimalsIndexRoute
  '/contacts/': typeof AuthedContactsIndexRoute
  '/drugs/': typeof AuthedDrugsIndexRoute
  '/orders/': typeof AuthedOrdersIndexRoute
  '/payments/': typeof AuthedPaymentsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/sponsorships/': typeof AuthedSponsorshipsIndexRoute
  '/animals/$animalId/edit': typeof AuthedAnimalsAnimalIdEditRoute
  '/animals/herds/$herdId': typeof AuthedAnimalsHerdsHerdIdRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/drugs/$drugId/edit': typeof AuthedDrugsDrugIdEditRoute
  '/field-calendar/crop-protection-applications/create': typeof AuthedFieldCalendarCropProtectionApplicationsCreateRoute
  '/field-calendar/crop-rotations/create': typeof AuthedFieldCalendarCropRotationsCreateRoute
  '/field-calendar/fertilizer-applications/create': typeof AuthedFieldCalendarFertilizerApplicationsCreateRoute
  '/field-calendar/harvests/$harvestId': typeof AuthedFieldCalendarHarvestsHarvestIdRoute
  '/field-calendar/harvests/create': typeof AuthedFieldCalendarHarvestsCreateRoute
  '/field-calendar/plots/$plotId': typeof AuthedFieldCalendarPlotsPlotIdRoute
  '/field-calendar/tillages/$tillageId': typeof AuthedFieldCalendarTillagesTillageIdRouteWithChildren
  '/field-calendar/tillages/create': typeof AuthedFieldCalendarTillagesCreateRoute
  '/orders/$orderId/edit': typeof AuthedOrdersOrderIdEditRoute
  '/payments/$paymentId/edit': typeof AuthedPaymentsPaymentIdEditRoute
  '/products/$productId/edit': typeof AuthedProductsProductIdEditRoute
  '/sponsorships/$sponsorshipId/edit': typeof AuthedSponsorshipsSponsorshipIdEditRoute
  '/sponsorships/programs/create': typeof AuthedSponsorshipsProgramsCreateRoute
  '/treatments/$treatmentId/edit': typeof AuthedTreatmentsTreatmentIdEditRoute
  '/animals/$animalId/': typeof AuthedAnimalsAnimalIdIndexRoute
  '/contacts/$contactId/': typeof AuthedContactsContactIdIndexRoute
  '/drugs/$drugId/': typeof AuthedDrugsDrugIdIndexRoute
  '/orders/$orderId/': typeof AuthedOrdersOrderIdIndexRoute
  '/payments/$paymentId/': typeof AuthedPaymentsPaymentIdIndexRoute
  '/products/$productId/': typeof AuthedProductsProductIdIndexRoute
  '/sponsorships/$sponsorshipId/': typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  '/sponsorships/programs/': typeof AuthedSponsorshipsProgramsIndexRoute
  '/treatments/$treatmentId/': typeof AuthedTreatmentsTreatmentIdIndexRoute
  '/field-calendar/crop-protection-applications/$id/edit': typeof AuthedFieldCalendarCropProtectionApplicationsIdEditRoute
  '/field-calendar/crop-rotations/$rotationId/edit': typeof AuthedFieldCalendarCropRotationsRotationIdEditRoute
  '/field-calendar/tillages/$tillageId/edit': typeof AuthedFieldCalendarTillagesTillageIdEditRoute
  '/sponsorships/programs/$programId/edit': typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  '/sponsorships/programs/$programId/': typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthedAccountRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/animals/create': typeof AuthedAnimalsCreateRoute
  '/animals/ear-tags': typeof AuthedAnimalsEarTagsRoute
  '/animals/herds': typeof AuthedAnimalsHerdsRoute
  '/animals/treatments-journal': typeof AuthedAnimalsTreatmentsJournalRoute
  '/animals/turnout-journal': typeof AuthedAnimalsTurnoutJournalRoute
  '/contacts/create': typeof AuthedContactsCreateRoute
  '/drugs/create': typeof AuthedDrugsCreateRoute
  '/field-calendar/crop-protection-applications': typeof AuthedFieldCalendarCropProtectionApplicationsRoute
  '/field-calendar/crop-rotations': typeof AuthedFieldCalendarCropRotationsRoute
  '/field-calendar/fertilizer-applications': typeof AuthedFieldCalendarFertilizerApplicationsRoute
  '/field-calendar/harvests': typeof AuthedFieldCalendarHarvestsRoute
  '/field-calendar/plots': typeof AuthedFieldCalendarPlotsRoute
  '/field-calendar/tillages': typeof AuthedFieldCalendarTillagesRoute
  '/orders/create': typeof AuthedOrdersCreateRoute
  '/payments/create': typeof AuthedPaymentsCreateRoute
  '/products/create': typeof AuthedProductsCreateRoute
  '/sponsorships/create': typeof AuthedSponsorshipsCreateRoute
  '/treatments/create': typeof AuthedTreatmentsCreateRoute
  '/animals': typeof AuthedAnimalsIndexRoute
  '/contacts': typeof AuthedContactsIndexRoute
  '/drugs': typeof AuthedDrugsIndexRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/payments': typeof AuthedPaymentsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/sponsorships': typeof AuthedSponsorshipsIndexRoute
  '/animals/$animalId/edit': typeof AuthedAnimalsAnimalIdEditRoute
  '/animals/herds/$herdId': typeof AuthedAnimalsHerdsHerdIdRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/drugs/$drugId/edit': typeof AuthedDrugsDrugIdEditRoute
  '/field-calendar/crop-protection-applications/create': typeof AuthedFieldCalendarCropProtectionApplicationsCreateRoute
  '/field-calendar/crop-rotations/create': typeof AuthedFieldCalendarCropRotationsCreateRoute
  '/field-calendar/fertilizer-applications/create': typeof AuthedFieldCalendarFertilizerApplicationsCreateRoute
  '/field-calendar/harvests/$harvestId': typeof AuthedFieldCalendarHarvestsHarvestIdRoute
  '/field-calendar/harvests/create': typeof AuthedFieldCalendarHarvestsCreateRoute
  '/field-calendar/plots/$plotId': typeof AuthedFieldCalendarPlotsPlotIdRoute
  '/field-calendar/tillages/$tillageId': typeof AuthedFieldCalendarTillagesTillageIdRouteWithChildren
  '/field-calendar/tillages/create': typeof AuthedFieldCalendarTillagesCreateRoute
  '/orders/$orderId/edit': typeof AuthedOrdersOrderIdEditRoute
  '/payments/$paymentId/edit': typeof AuthedPaymentsPaymentIdEditRoute
  '/products/$productId/edit': typeof AuthedProductsProductIdEditRoute
  '/sponsorships/$sponsorshipId/edit': typeof AuthedSponsorshipsSponsorshipIdEditRoute
  '/sponsorships/programs/create': typeof AuthedSponsorshipsProgramsCreateRoute
  '/treatments/$treatmentId/edit': typeof AuthedTreatmentsTreatmentIdEditRoute
  '/animals/$animalId': typeof AuthedAnimalsAnimalIdIndexRoute
  '/contacts/$contactId': typeof AuthedContactsContactIdIndexRoute
  '/drugs/$drugId': typeof AuthedDrugsDrugIdIndexRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdIndexRoute
  '/payments/$paymentId': typeof AuthedPaymentsPaymentIdIndexRoute
  '/products/$productId': typeof AuthedProductsProductIdIndexRoute
  '/sponsorships/$sponsorshipId': typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  '/sponsorships/programs': typeof AuthedSponsorshipsProgramsIndexRoute
  '/treatments/$treatmentId': typeof AuthedTreatmentsTreatmentIdIndexRoute
  '/field-calendar/crop-protection-applications/$id/edit': typeof AuthedFieldCalendarCropProtectionApplicationsIdEditRoute
  '/field-calendar/crop-rotations/$rotationId/edit': typeof AuthedFieldCalendarCropRotationsRotationIdEditRoute
  '/field-calendar/tillages/$tillageId/edit': typeof AuthedFieldCalendarTillagesTillageIdEditRoute
  '/sponsorships/programs/$programId/edit': typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  '/sponsorships/programs/$programId': typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/animals/create': typeof AuthedAnimalsCreateRoute
  '/_authed/animals/ear-tags': typeof AuthedAnimalsEarTagsRoute
  '/_authed/animals/herds': typeof AuthedAnimalsHerdsRoute
  '/_authed/animals/treatments-journal': typeof AuthedAnimalsTreatmentsJournalRoute
  '/_authed/animals/turnout-journal': typeof AuthedAnimalsTurnoutJournalRoute
  '/_authed/contacts/create': typeof AuthedContactsCreateRoute
  '/_authed/drugs/create': typeof AuthedDrugsCreateRoute
  '/_authed/field-calendar/crop-protection-applications': typeof AuthedFieldCalendarCropProtectionApplicationsRoute
  '/_authed/field-calendar/crop-rotations': typeof AuthedFieldCalendarCropRotationsRoute
  '/_authed/field-calendar/fertilizer-applications': typeof AuthedFieldCalendarFertilizerApplicationsRoute
  '/_authed/field-calendar/harvests': typeof AuthedFieldCalendarHarvestsRoute
  '/_authed/field-calendar/plots': typeof AuthedFieldCalendarPlotsRoute
  '/_authed/field-calendar/tillages': typeof AuthedFieldCalendarTillagesRoute
  '/_authed/orders/create': typeof AuthedOrdersCreateRoute
  '/_authed/payments/create': typeof AuthedPaymentsCreateRoute
  '/_authed/products/create': typeof AuthedProductsCreateRoute
  '/_authed/sponsorships/create': typeof AuthedSponsorshipsCreateRoute
  '/_authed/treatments/create': typeof AuthedTreatmentsCreateRoute
  '/_authed/animals/': typeof AuthedAnimalsIndexRoute
  '/_authed/contacts/': typeof AuthedContactsIndexRoute
  '/_authed/drugs/': typeof AuthedDrugsIndexRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/payments/': typeof AuthedPaymentsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/sponsorships/': typeof AuthedSponsorshipsIndexRoute
  '/_authed/animals/$animalId/edit': typeof AuthedAnimalsAnimalIdEditRoute
  '/_authed/animals/herds_/$herdId': typeof AuthedAnimalsHerdsHerdIdRoute
  '/_authed/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/_authed/drugs/$drugId/edit': typeof AuthedDrugsDrugIdEditRoute
  '/_authed/field-calendar/crop-protection-applications_/create': typeof AuthedFieldCalendarCropProtectionApplicationsCreateRoute
  '/_authed/field-calendar/crop-rotations_/create': typeof AuthedFieldCalendarCropRotationsCreateRoute
  '/_authed/field-calendar/fertilizer-applications_/create': typeof AuthedFieldCalendarFertilizerApplicationsCreateRoute
  '/_authed/field-calendar/harvests_/$harvestId': typeof AuthedFieldCalendarHarvestsHarvestIdRoute
  '/_authed/field-calendar/harvests_/create': typeof AuthedFieldCalendarHarvestsCreateRoute
  '/_authed/field-calendar/plots_/$plotId': typeof AuthedFieldCalendarPlotsPlotIdRoute
  '/_authed/field-calendar/tillages_/$tillageId': typeof AuthedFieldCalendarTillagesTillageIdRouteWithChildren
  '/_authed/field-calendar/tillages_/create': typeof AuthedFieldCalendarTillagesCreateRoute
  '/_authed/orders/$orderId/edit': typeof AuthedOrdersOrderIdEditRoute
  '/_authed/payments/$paymentId/edit': typeof AuthedPaymentsPaymentIdEditRoute
  '/_authed/products/$productId/edit': typeof AuthedProductsProductIdEditRoute
  '/_authed/sponsorships/$sponsorshipId/edit': typeof AuthedSponsorshipsSponsorshipIdEditRoute
  '/_authed/sponsorships/programs/create': typeof AuthedSponsorshipsProgramsCreateRoute
  '/_authed/treatments/$treatmentId/edit': typeof AuthedTreatmentsTreatmentIdEditRoute
  '/_authed/animals/$animalId/': typeof AuthedAnimalsAnimalIdIndexRoute
  '/_authed/contacts/$contactId/': typeof AuthedContactsContactIdIndexRoute
  '/_authed/drugs/$drugId/': typeof AuthedDrugsDrugIdIndexRoute
  '/_authed/orders/$orderId/': typeof AuthedOrdersOrderIdIndexRoute
  '/_authed/payments/$paymentId/': typeof AuthedPaymentsPaymentIdIndexRoute
  '/_authed/products/$productId/': typeof AuthedProductsProductIdIndexRoute
  '/_authed/sponsorships/$sponsorshipId/': typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  '/_authed/sponsorships/programs/': typeof AuthedSponsorshipsProgramsIndexRoute
  '/_authed/treatments/$treatmentId/': typeof AuthedTreatmentsTreatmentIdIndexRoute
  '/_authed/field-calendar/crop-protection-applications_/$id/edit': typeof AuthedFieldCalendarCropProtectionApplicationsIdEditRoute
  '/_authed/field-calendar/crop-rotations_/$rotationId/edit': typeof AuthedFieldCalendarCropRotationsRotationIdEditRoute
  '/_authed/field-calendar/tillages_/$tillageId/edit': typeof AuthedFieldCalendarTillagesTillageIdEditRoute
  '/_authed/sponsorships/programs/$programId/edit': typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  '/_authed/sponsorships/programs/$programId/': typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-deletion'
    | '/forgot-password'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/dashboard'
    | '/settings'
    | '/animals/create'
    | '/animals/ear-tags'
    | '/animals/herds'
    | '/animals/treatments-journal'
    | '/animals/turnout-journal'
    | '/contacts/create'
    | '/drugs/create'
    | '/field-calendar/crop-protection-applications'
    | '/field-calendar/crop-rotations'
    | '/field-calendar/fertilizer-applications'
    | '/field-calendar/harvests'
    | '/field-calendar/plots'
    | '/field-calendar/tillages'
    | '/orders/create'
    | '/payments/create'
    | '/products/create'
    | '/sponsorships/create'
    | '/treatments/create'
    | '/animals/'
    | '/contacts/'
    | '/drugs/'
    | '/orders/'
    | '/payments/'
    | '/products/'
    | '/sponsorships/'
    | '/animals/$animalId/edit'
    | '/animals/herds/$herdId'
    | '/contacts/$contactId/edit'
    | '/drugs/$drugId/edit'
    | '/field-calendar/crop-protection-applications/create'
    | '/field-calendar/crop-rotations/create'
    | '/field-calendar/fertilizer-applications/create'
    | '/field-calendar/harvests/$harvestId'
    | '/field-calendar/harvests/create'
    | '/field-calendar/plots/$plotId'
    | '/field-calendar/tillages/$tillageId'
    | '/field-calendar/tillages/create'
    | '/orders/$orderId/edit'
    | '/payments/$paymentId/edit'
    | '/products/$productId/edit'
    | '/sponsorships/$sponsorshipId/edit'
    | '/sponsorships/programs/create'
    | '/treatments/$treatmentId/edit'
    | '/animals/$animalId/'
    | '/contacts/$contactId/'
    | '/drugs/$drugId/'
    | '/orders/$orderId/'
    | '/payments/$paymentId/'
    | '/products/$productId/'
    | '/sponsorships/$sponsorshipId/'
    | '/sponsorships/programs/'
    | '/treatments/$treatmentId/'
    | '/field-calendar/crop-protection-applications/$id/edit'
    | '/field-calendar/crop-rotations/$rotationId/edit'
    | '/field-calendar/tillages/$tillageId/edit'
    | '/sponsorships/programs/$programId/edit'
    | '/sponsorships/programs/$programId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/forgot-password'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/account'
    | '/dashboard'
    | '/settings'
    | '/animals/create'
    | '/animals/ear-tags'
    | '/animals/herds'
    | '/animals/treatments-journal'
    | '/animals/turnout-journal'
    | '/contacts/create'
    | '/drugs/create'
    | '/field-calendar/crop-protection-applications'
    | '/field-calendar/crop-rotations'
    | '/field-calendar/fertilizer-applications'
    | '/field-calendar/harvests'
    | '/field-calendar/plots'
    | '/field-calendar/tillages'
    | '/orders/create'
    | '/payments/create'
    | '/products/create'
    | '/sponsorships/create'
    | '/treatments/create'
    | '/animals'
    | '/contacts'
    | '/drugs'
    | '/orders'
    | '/payments'
    | '/products'
    | '/sponsorships'
    | '/animals/$animalId/edit'
    | '/animals/herds/$herdId'
    | '/contacts/$contactId/edit'
    | '/drugs/$drugId/edit'
    | '/field-calendar/crop-protection-applications/create'
    | '/field-calendar/crop-rotations/create'
    | '/field-calendar/fertilizer-applications/create'
    | '/field-calendar/harvests/$harvestId'
    | '/field-calendar/harvests/create'
    | '/field-calendar/plots/$plotId'
    | '/field-calendar/tillages/$tillageId'
    | '/field-calendar/tillages/create'
    | '/orders/$orderId/edit'
    | '/payments/$paymentId/edit'
    | '/products/$productId/edit'
    | '/sponsorships/$sponsorshipId/edit'
    | '/sponsorships/programs/create'
    | '/treatments/$treatmentId/edit'
    | '/animals/$animalId'
    | '/contacts/$contactId'
    | '/drugs/$drugId'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/products/$productId'
    | '/sponsorships/$sponsorshipId'
    | '/sponsorships/programs'
    | '/treatments/$treatmentId'
    | '/field-calendar/crop-protection-applications/$id/edit'
    | '/field-calendar/crop-rotations/$rotationId/edit'
    | '/field-calendar/tillages/$tillageId/edit'
    | '/sponsorships/programs/$programId/edit'
    | '/sponsorships/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/data-deletion'
    | '/forgot-password'
    | '/imprint'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/_authed/account'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/_authed/animals/create'
    | '/_authed/animals/ear-tags'
    | '/_authed/animals/herds'
    | '/_authed/animals/treatments-journal'
    | '/_authed/animals/turnout-journal'
    | '/_authed/contacts/create'
    | '/_authed/drugs/create'
    | '/_authed/field-calendar/crop-protection-applications'
    | '/_authed/field-calendar/crop-rotations'
    | '/_authed/field-calendar/fertilizer-applications'
    | '/_authed/field-calendar/harvests'
    | '/_authed/field-calendar/plots'
    | '/_authed/field-calendar/tillages'
    | '/_authed/orders/create'
    | '/_authed/payments/create'
    | '/_authed/products/create'
    | '/_authed/sponsorships/create'
    | '/_authed/treatments/create'
    | '/_authed/animals/'
    | '/_authed/contacts/'
    | '/_authed/drugs/'
    | '/_authed/orders/'
    | '/_authed/payments/'
    | '/_authed/products/'
    | '/_authed/sponsorships/'
    | '/_authed/animals/$animalId/edit'
    | '/_authed/animals/herds_/$herdId'
    | '/_authed/contacts/$contactId/edit'
    | '/_authed/drugs/$drugId/edit'
    | '/_authed/field-calendar/crop-protection-applications_/create'
    | '/_authed/field-calendar/crop-rotations_/create'
    | '/_authed/field-calendar/fertilizer-applications_/create'
    | '/_authed/field-calendar/harvests_/$harvestId'
    | '/_authed/field-calendar/harvests_/create'
    | '/_authed/field-calendar/plots_/$plotId'
    | '/_authed/field-calendar/tillages_/$tillageId'
    | '/_authed/field-calendar/tillages_/create'
    | '/_authed/orders/$orderId/edit'
    | '/_authed/payments/$paymentId/edit'
    | '/_authed/products/$productId/edit'
    | '/_authed/sponsorships/$sponsorshipId/edit'
    | '/_authed/sponsorships/programs/create'
    | '/_authed/treatments/$treatmentId/edit'
    | '/_authed/animals/$animalId/'
    | '/_authed/contacts/$contactId/'
    | '/_authed/drugs/$drugId/'
    | '/_authed/orders/$orderId/'
    | '/_authed/payments/$paymentId/'
    | '/_authed/products/$productId/'
    | '/_authed/sponsorships/$sponsorshipId/'
    | '/_authed/sponsorships/programs/'
    | '/_authed/treatments/$treatmentId/'
    | '/_authed/field-calendar/crop-protection-applications_/$id/edit'
    | '/_authed/field-calendar/crop-rotations_/$rotationId/edit'
    | '/_authed/field-calendar/tillages_/$tillageId/edit'
    | '/_authed/sponsorships/programs/$programId/edit'
    | '/_authed/sponsorships/programs/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImprintRoute: typeof ImprintRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/': {
      id: '/_authed/sponsorships/'
      path: '/sponsorships'
      fullPath: '/sponsorships/'
      preLoaderRoute: typeof AuthedSponsorshipsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/': {
      id: '/_authed/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthedPaymentsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/drugs/': {
      id: '/_authed/drugs/'
      path: '/drugs'
      fullPath: '/drugs/'
      preLoaderRoute: typeof AuthedDrugsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/': {
      id: '/_authed/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthedContactsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/': {
      id: '/_authed/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AuthedAnimalsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/treatments/create': {
      id: '/_authed/treatments/create'
      path: '/treatments/create'
      fullPath: '/treatments/create'
      preLoaderRoute: typeof AuthedTreatmentsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/create': {
      id: '/_authed/sponsorships/create'
      path: '/sponsorships/create'
      fullPath: '/sponsorships/create'
      preLoaderRoute: typeof AuthedSponsorshipsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/create': {
      id: '/_authed/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof AuthedProductsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/create': {
      id: '/_authed/payments/create'
      path: '/payments/create'
      fullPath: '/payments/create'
      preLoaderRoute: typeof AuthedPaymentsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/create': {
      id: '/_authed/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof AuthedOrdersCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/tillages': {
      id: '/_authed/field-calendar/tillages'
      path: '/field-calendar/tillages'
      fullPath: '/field-calendar/tillages'
      preLoaderRoute: typeof AuthedFieldCalendarTillagesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/plots': {
      id: '/_authed/field-calendar/plots'
      path: '/field-calendar/plots'
      fullPath: '/field-calendar/plots'
      preLoaderRoute: typeof AuthedFieldCalendarPlotsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/harvests': {
      id: '/_authed/field-calendar/harvests'
      path: '/field-calendar/harvests'
      fullPath: '/field-calendar/harvests'
      preLoaderRoute: typeof AuthedFieldCalendarHarvestsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/fertilizer-applications': {
      id: '/_authed/field-calendar/fertilizer-applications'
      path: '/field-calendar/fertilizer-applications'
      fullPath: '/field-calendar/fertilizer-applications'
      preLoaderRoute: typeof AuthedFieldCalendarFertilizerApplicationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/crop-rotations': {
      id: '/_authed/field-calendar/crop-rotations'
      path: '/field-calendar/crop-rotations'
      fullPath: '/field-calendar/crop-rotations'
      preLoaderRoute: typeof AuthedFieldCalendarCropRotationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/crop-protection-applications': {
      id: '/_authed/field-calendar/crop-protection-applications'
      path: '/field-calendar/crop-protection-applications'
      fullPath: '/field-calendar/crop-protection-applications'
      preLoaderRoute: typeof AuthedFieldCalendarCropProtectionApplicationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/drugs/create': {
      id: '/_authed/drugs/create'
      path: '/drugs/create'
      fullPath: '/drugs/create'
      preLoaderRoute: typeof AuthedDrugsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/create': {
      id: '/_authed/contacts/create'
      path: '/contacts/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof AuthedContactsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/turnout-journal': {
      id: '/_authed/animals/turnout-journal'
      path: '/animals/turnout-journal'
      fullPath: '/animals/turnout-journal'
      preLoaderRoute: typeof AuthedAnimalsTurnoutJournalRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/treatments-journal': {
      id: '/_authed/animals/treatments-journal'
      path: '/animals/treatments-journal'
      fullPath: '/animals/treatments-journal'
      preLoaderRoute: typeof AuthedAnimalsTreatmentsJournalRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/herds': {
      id: '/_authed/animals/herds'
      path: '/animals/herds'
      fullPath: '/animals/herds'
      preLoaderRoute: typeof AuthedAnimalsHerdsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/ear-tags': {
      id: '/_authed/animals/ear-tags'
      path: '/animals/ear-tags'
      fullPath: '/animals/ear-tags'
      preLoaderRoute: typeof AuthedAnimalsEarTagsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/create': {
      id: '/_authed/animals/create'
      path: '/animals/create'
      fullPath: '/animals/create'
      preLoaderRoute: typeof AuthedAnimalsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/treatments/$treatmentId/': {
      id: '/_authed/treatments/$treatmentId/'
      path: '/treatments/$treatmentId'
      fullPath: '/treatments/$treatmentId/'
      preLoaderRoute: typeof AuthedTreatmentsTreatmentIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/': {
      id: '/_authed/sponsorships/programs/'
      path: '/sponsorships/programs'
      fullPath: '/sponsorships/programs/'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/$sponsorshipId/': {
      id: '/_authed/sponsorships/$sponsorshipId/'
      path: '/sponsorships/$sponsorshipId'
      fullPath: '/sponsorships/$sponsorshipId/'
      preLoaderRoute: typeof AuthedSponsorshipsSponsorshipIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$productId/': {
      id: '/_authed/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof AuthedProductsProductIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/$paymentId/': {
      id: '/_authed/payments/$paymentId/'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId/'
      preLoaderRoute: typeof AuthedPaymentsPaymentIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/$orderId/': {
      id: '/_authed/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof AuthedOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/drugs/$drugId/': {
      id: '/_authed/drugs/$drugId/'
      path: '/drugs/$drugId'
      fullPath: '/drugs/$drugId/'
      preLoaderRoute: typeof AuthedDrugsDrugIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/$contactId/': {
      id: '/_authed/contacts/$contactId/'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId/'
      preLoaderRoute: typeof AuthedContactsContactIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/$animalId/': {
      id: '/_authed/animals/$animalId/'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId/'
      preLoaderRoute: typeof AuthedAnimalsAnimalIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/treatments/$treatmentId/edit': {
      id: '/_authed/treatments/$treatmentId/edit'
      path: '/treatments/$treatmentId/edit'
      fullPath: '/treatments/$treatmentId/edit'
      preLoaderRoute: typeof AuthedTreatmentsTreatmentIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/create': {
      id: '/_authed/sponsorships/programs/create'
      path: '/sponsorships/programs/create'
      fullPath: '/sponsorships/programs/create'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/$sponsorshipId/edit': {
      id: '/_authed/sponsorships/$sponsorshipId/edit'
      path: '/sponsorships/$sponsorshipId/edit'
      fullPath: '/sponsorships/$sponsorshipId/edit'
      preLoaderRoute: typeof AuthedSponsorshipsSponsorshipIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$productId/edit': {
      id: '/_authed/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AuthedProductsProductIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/$paymentId/edit': {
      id: '/_authed/payments/$paymentId/edit'
      path: '/payments/$paymentId/edit'
      fullPath: '/payments/$paymentId/edit'
      preLoaderRoute: typeof AuthedPaymentsPaymentIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/$orderId/edit': {
      id: '/_authed/orders/$orderId/edit'
      path: '/orders/$orderId/edit'
      fullPath: '/orders/$orderId/edit'
      preLoaderRoute: typeof AuthedOrdersOrderIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/tillages_/create': {
      id: '/_authed/field-calendar/tillages_/create'
      path: '/field-calendar/tillages/create'
      fullPath: '/field-calendar/tillages/create'
      preLoaderRoute: typeof AuthedFieldCalendarTillagesCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/tillages_/$tillageId': {
      id: '/_authed/field-calendar/tillages_/$tillageId'
      path: '/field-calendar/tillages/$tillageId'
      fullPath: '/field-calendar/tillages/$tillageId'
      preLoaderRoute: typeof AuthedFieldCalendarTillagesTillageIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/plots_/$plotId': {
      id: '/_authed/field-calendar/plots_/$plotId'
      path: '/field-calendar/plots/$plotId'
      fullPath: '/field-calendar/plots/$plotId'
      preLoaderRoute: typeof AuthedFieldCalendarPlotsPlotIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/harvests_/create': {
      id: '/_authed/field-calendar/harvests_/create'
      path: '/field-calendar/harvests/create'
      fullPath: '/field-calendar/harvests/create'
      preLoaderRoute: typeof AuthedFieldCalendarHarvestsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/harvests_/$harvestId': {
      id: '/_authed/field-calendar/harvests_/$harvestId'
      path: '/field-calendar/harvests/$harvestId'
      fullPath: '/field-calendar/harvests/$harvestId'
      preLoaderRoute: typeof AuthedFieldCalendarHarvestsHarvestIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/fertilizer-applications_/create': {
      id: '/_authed/field-calendar/fertilizer-applications_/create'
      path: '/field-calendar/fertilizer-applications/create'
      fullPath: '/field-calendar/fertilizer-applications/create'
      preLoaderRoute: typeof AuthedFieldCalendarFertilizerApplicationsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/crop-rotations_/create': {
      id: '/_authed/field-calendar/crop-rotations_/create'
      path: '/field-calendar/crop-rotations/create'
      fullPath: '/field-calendar/crop-rotations/create'
      preLoaderRoute: typeof AuthedFieldCalendarCropRotationsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/crop-protection-applications_/create': {
      id: '/_authed/field-calendar/crop-protection-applications_/create'
      path: '/field-calendar/crop-protection-applications/create'
      fullPath: '/field-calendar/crop-protection-applications/create'
      preLoaderRoute: typeof AuthedFieldCalendarCropProtectionApplicationsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/drugs/$drugId/edit': {
      id: '/_authed/drugs/$drugId/edit'
      path: '/drugs/$drugId/edit'
      fullPath: '/drugs/$drugId/edit'
      preLoaderRoute: typeof AuthedDrugsDrugIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/$contactId/edit': {
      id: '/_authed/contacts/$contactId/edit'
      path: '/contacts/$contactId/edit'
      fullPath: '/contacts/$contactId/edit'
      preLoaderRoute: typeof AuthedContactsContactIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/herds_/$herdId': {
      id: '/_authed/animals/herds_/$herdId'
      path: '/animals/herds/$herdId'
      fullPath: '/animals/herds/$herdId'
      preLoaderRoute: typeof AuthedAnimalsHerdsHerdIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/$animalId/edit': {
      id: '/_authed/animals/$animalId/edit'
      path: '/animals/$animalId/edit'
      fullPath: '/animals/$animalId/edit'
      preLoaderRoute: typeof AuthedAnimalsAnimalIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/$programId/': {
      id: '/_authed/sponsorships/programs/$programId/'
      path: '/sponsorships/programs/$programId'
      fullPath: '/sponsorships/programs/$programId/'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsProgramIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/$programId/edit': {
      id: '/_authed/sponsorships/programs/$programId/edit'
      path: '/sponsorships/programs/$programId/edit'
      fullPath: '/sponsorships/programs/$programId/edit'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsProgramIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/tillages_/$tillageId/edit': {
      id: '/_authed/field-calendar/tillages_/$tillageId/edit'
      path: '/edit'
      fullPath: '/field-calendar/tillages/$tillageId/edit'
      preLoaderRoute: typeof AuthedFieldCalendarTillagesTillageIdEditRouteImport
      parentRoute: typeof AuthedFieldCalendarTillagesTillageIdRoute
    }
    '/_authed/field-calendar/crop-rotations_/$rotationId/edit': {
      id: '/_authed/field-calendar/crop-rotations_/$rotationId/edit'
      path: '/field-calendar/crop-rotations/$rotationId/edit'
      fullPath: '/field-calendar/crop-rotations/$rotationId/edit'
      preLoaderRoute: typeof AuthedFieldCalendarCropRotationsRotationIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/field-calendar/crop-protection-applications_/$id/edit': {
      id: '/_authed/field-calendar/crop-protection-applications_/$id/edit'
      path: '/field-calendar/crop-protection-applications/$id/edit'
      fullPath: '/field-calendar/crop-protection-applications/$id/edit'
      preLoaderRoute: typeof AuthedFieldCalendarCropProtectionApplicationsIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedFieldCalendarTillagesTillageIdRouteChildren {
  AuthedFieldCalendarTillagesTillageIdEditRoute: typeof AuthedFieldCalendarTillagesTillageIdEditRoute
}

const AuthedFieldCalendarTillagesTillageIdRouteChildren: AuthedFieldCalendarTillagesTillageIdRouteChildren =
  {
    AuthedFieldCalendarTillagesTillageIdEditRoute:
      AuthedFieldCalendarTillagesTillageIdEditRoute,
  }

const AuthedFieldCalendarTillagesTillageIdRouteWithChildren =
  AuthedFieldCalendarTillagesTillageIdRoute._addFileChildren(
    AuthedFieldCalendarTillagesTillageIdRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedAnimalsCreateRoute: typeof AuthedAnimalsCreateRoute
  AuthedAnimalsEarTagsRoute: typeof AuthedAnimalsEarTagsRoute
  AuthedAnimalsHerdsRoute: typeof AuthedAnimalsHerdsRoute
  AuthedAnimalsTreatmentsJournalRoute: typeof AuthedAnimalsTreatmentsJournalRoute
  AuthedAnimalsTurnoutJournalRoute: typeof AuthedAnimalsTurnoutJournalRoute
  AuthedContactsCreateRoute: typeof AuthedContactsCreateRoute
  AuthedDrugsCreateRoute: typeof AuthedDrugsCreateRoute
  AuthedFieldCalendarCropProtectionApplicationsRoute: typeof AuthedFieldCalendarCropProtectionApplicationsRoute
  AuthedFieldCalendarCropRotationsRoute: typeof AuthedFieldCalendarCropRotationsRoute
  AuthedFieldCalendarFertilizerApplicationsRoute: typeof AuthedFieldCalendarFertilizerApplicationsRoute
  AuthedFieldCalendarHarvestsRoute: typeof AuthedFieldCalendarHarvestsRoute
  AuthedFieldCalendarPlotsRoute: typeof AuthedFieldCalendarPlotsRoute
  AuthedFieldCalendarTillagesRoute: typeof AuthedFieldCalendarTillagesRoute
  AuthedOrdersCreateRoute: typeof AuthedOrdersCreateRoute
  AuthedPaymentsCreateRoute: typeof AuthedPaymentsCreateRoute
  AuthedProductsCreateRoute: typeof AuthedProductsCreateRoute
  AuthedSponsorshipsCreateRoute: typeof AuthedSponsorshipsCreateRoute
  AuthedTreatmentsCreateRoute: typeof AuthedTreatmentsCreateRoute
  AuthedAnimalsIndexRoute: typeof AuthedAnimalsIndexRoute
  AuthedContactsIndexRoute: typeof AuthedContactsIndexRoute
  AuthedDrugsIndexRoute: typeof AuthedDrugsIndexRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedPaymentsIndexRoute: typeof AuthedPaymentsIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedSponsorshipsIndexRoute: typeof AuthedSponsorshipsIndexRoute
  AuthedAnimalsAnimalIdEditRoute: typeof AuthedAnimalsAnimalIdEditRoute
  AuthedAnimalsHerdsHerdIdRoute: typeof AuthedAnimalsHerdsHerdIdRoute
  AuthedContactsContactIdEditRoute: typeof AuthedContactsContactIdEditRoute
  AuthedDrugsDrugIdEditRoute: typeof AuthedDrugsDrugIdEditRoute
  AuthedFieldCalendarCropProtectionApplicationsCreateRoute: typeof AuthedFieldCalendarCropProtectionApplicationsCreateRoute
  AuthedFieldCalendarCropRotationsCreateRoute: typeof AuthedFieldCalendarCropRotationsCreateRoute
  AuthedFieldCalendarFertilizerApplicationsCreateRoute: typeof AuthedFieldCalendarFertilizerApplicationsCreateRoute
  AuthedFieldCalendarHarvestsHarvestIdRoute: typeof AuthedFieldCalendarHarvestsHarvestIdRoute
  AuthedFieldCalendarHarvestsCreateRoute: typeof AuthedFieldCalendarHarvestsCreateRoute
  AuthedFieldCalendarPlotsPlotIdRoute: typeof AuthedFieldCalendarPlotsPlotIdRoute
  AuthedFieldCalendarTillagesTillageIdRoute: typeof AuthedFieldCalendarTillagesTillageIdRouteWithChildren
  AuthedFieldCalendarTillagesCreateRoute: typeof AuthedFieldCalendarTillagesCreateRoute
  AuthedOrdersOrderIdEditRoute: typeof AuthedOrdersOrderIdEditRoute
  AuthedPaymentsPaymentIdEditRoute: typeof AuthedPaymentsPaymentIdEditRoute
  AuthedProductsProductIdEditRoute: typeof AuthedProductsProductIdEditRoute
  AuthedSponsorshipsSponsorshipIdEditRoute: typeof AuthedSponsorshipsSponsorshipIdEditRoute
  AuthedSponsorshipsProgramsCreateRoute: typeof AuthedSponsorshipsProgramsCreateRoute
  AuthedTreatmentsTreatmentIdEditRoute: typeof AuthedTreatmentsTreatmentIdEditRoute
  AuthedAnimalsAnimalIdIndexRoute: typeof AuthedAnimalsAnimalIdIndexRoute
  AuthedContactsContactIdIndexRoute: typeof AuthedContactsContactIdIndexRoute
  AuthedDrugsDrugIdIndexRoute: typeof AuthedDrugsDrugIdIndexRoute
  AuthedOrdersOrderIdIndexRoute: typeof AuthedOrdersOrderIdIndexRoute
  AuthedPaymentsPaymentIdIndexRoute: typeof AuthedPaymentsPaymentIdIndexRoute
  AuthedProductsProductIdIndexRoute: typeof AuthedProductsProductIdIndexRoute
  AuthedSponsorshipsSponsorshipIdIndexRoute: typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  AuthedSponsorshipsProgramsIndexRoute: typeof AuthedSponsorshipsProgramsIndexRoute
  AuthedTreatmentsTreatmentIdIndexRoute: typeof AuthedTreatmentsTreatmentIdIndexRoute
  AuthedFieldCalendarCropProtectionApplicationsIdEditRoute: typeof AuthedFieldCalendarCropProtectionApplicationsIdEditRoute
  AuthedFieldCalendarCropRotationsRotationIdEditRoute: typeof AuthedFieldCalendarCropRotationsRotationIdEditRoute
  AuthedSponsorshipsProgramsProgramIdEditRoute: typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  AuthedSponsorshipsProgramsProgramIdIndexRoute: typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedAnimalsCreateRoute: AuthedAnimalsCreateRoute,
  AuthedAnimalsEarTagsRoute: AuthedAnimalsEarTagsRoute,
  AuthedAnimalsHerdsRoute: AuthedAnimalsHerdsRoute,
  AuthedAnimalsTreatmentsJournalRoute: AuthedAnimalsTreatmentsJournalRoute,
  AuthedAnimalsTurnoutJournalRoute: AuthedAnimalsTurnoutJournalRoute,
  AuthedContactsCreateRoute: AuthedContactsCreateRoute,
  AuthedDrugsCreateRoute: AuthedDrugsCreateRoute,
  AuthedFieldCalendarCropProtectionApplicationsRoute:
    AuthedFieldCalendarCropProtectionApplicationsRoute,
  AuthedFieldCalendarCropRotationsRoute: AuthedFieldCalendarCropRotationsRoute,
  AuthedFieldCalendarFertilizerApplicationsRoute:
    AuthedFieldCalendarFertilizerApplicationsRoute,
  AuthedFieldCalendarHarvestsRoute: AuthedFieldCalendarHarvestsRoute,
  AuthedFieldCalendarPlotsRoute: AuthedFieldCalendarPlotsRoute,
  AuthedFieldCalendarTillagesRoute: AuthedFieldCalendarTillagesRoute,
  AuthedOrdersCreateRoute: AuthedOrdersCreateRoute,
  AuthedPaymentsCreateRoute: AuthedPaymentsCreateRoute,
  AuthedProductsCreateRoute: AuthedProductsCreateRoute,
  AuthedSponsorshipsCreateRoute: AuthedSponsorshipsCreateRoute,
  AuthedTreatmentsCreateRoute: AuthedTreatmentsCreateRoute,
  AuthedAnimalsIndexRoute: AuthedAnimalsIndexRoute,
  AuthedContactsIndexRoute: AuthedContactsIndexRoute,
  AuthedDrugsIndexRoute: AuthedDrugsIndexRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedPaymentsIndexRoute: AuthedPaymentsIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedSponsorshipsIndexRoute: AuthedSponsorshipsIndexRoute,
  AuthedAnimalsAnimalIdEditRoute: AuthedAnimalsAnimalIdEditRoute,
  AuthedAnimalsHerdsHerdIdRoute: AuthedAnimalsHerdsHerdIdRoute,
  AuthedContactsContactIdEditRoute: AuthedContactsContactIdEditRoute,
  AuthedDrugsDrugIdEditRoute: AuthedDrugsDrugIdEditRoute,
  AuthedFieldCalendarCropProtectionApplicationsCreateRoute:
    AuthedFieldCalendarCropProtectionApplicationsCreateRoute,
  AuthedFieldCalendarCropRotationsCreateRoute:
    AuthedFieldCalendarCropRotationsCreateRoute,
  AuthedFieldCalendarFertilizerApplicationsCreateRoute:
    AuthedFieldCalendarFertilizerApplicationsCreateRoute,
  AuthedFieldCalendarHarvestsHarvestIdRoute:
    AuthedFieldCalendarHarvestsHarvestIdRoute,
  AuthedFieldCalendarHarvestsCreateRoute:
    AuthedFieldCalendarHarvestsCreateRoute,
  AuthedFieldCalendarPlotsPlotIdRoute: AuthedFieldCalendarPlotsPlotIdRoute,
  AuthedFieldCalendarTillagesTillageIdRoute:
    AuthedFieldCalendarTillagesTillageIdRouteWithChildren,
  AuthedFieldCalendarTillagesCreateRoute:
    AuthedFieldCalendarTillagesCreateRoute,
  AuthedOrdersOrderIdEditRoute: AuthedOrdersOrderIdEditRoute,
  AuthedPaymentsPaymentIdEditRoute: AuthedPaymentsPaymentIdEditRoute,
  AuthedProductsProductIdEditRoute: AuthedProductsProductIdEditRoute,
  AuthedSponsorshipsSponsorshipIdEditRoute:
    AuthedSponsorshipsSponsorshipIdEditRoute,
  AuthedSponsorshipsProgramsCreateRoute: AuthedSponsorshipsProgramsCreateRoute,
  AuthedTreatmentsTreatmentIdEditRoute: AuthedTreatmentsTreatmentIdEditRoute,
  AuthedAnimalsAnimalIdIndexRoute: AuthedAnimalsAnimalIdIndexRoute,
  AuthedContactsContactIdIndexRoute: AuthedContactsContactIdIndexRoute,
  AuthedDrugsDrugIdIndexRoute: AuthedDrugsDrugIdIndexRoute,
  AuthedOrdersOrderIdIndexRoute: AuthedOrdersOrderIdIndexRoute,
  AuthedPaymentsPaymentIdIndexRoute: AuthedPaymentsPaymentIdIndexRoute,
  AuthedProductsProductIdIndexRoute: AuthedProductsProductIdIndexRoute,
  AuthedSponsorshipsSponsorshipIdIndexRoute:
    AuthedSponsorshipsSponsorshipIdIndexRoute,
  AuthedSponsorshipsProgramsIndexRoute: AuthedSponsorshipsProgramsIndexRoute,
  AuthedTreatmentsTreatmentIdIndexRoute: AuthedTreatmentsTreatmentIdIndexRoute,
  AuthedFieldCalendarCropProtectionApplicationsIdEditRoute:
    AuthedFieldCalendarCropProtectionApplicationsIdEditRoute,
  AuthedFieldCalendarCropRotationsRotationIdEditRoute:
    AuthedFieldCalendarCropRotationsRotationIdEditRoute,
  AuthedSponsorshipsProgramsProgramIdEditRoute:
    AuthedSponsorshipsProgramsProgramIdEditRoute,
  AuthedSponsorshipsProgramsProgramIdIndexRoute:
    AuthedSponsorshipsProgramsProgramIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImprintRoute: ImprintRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
