/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSponsorshipsIndexRouteImport } from './routes/_authed/sponsorships/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedPaymentsIndexRouteImport } from './routes/_authed/payments/index'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders/index'
import { Route as AuthedContactsIndexRouteImport } from './routes/_authed/contacts/index'
import { Route as AuthedAnimalsIndexRouteImport } from './routes/_authed/animals/index'
import { Route as AuthedSponsorshipsCreateRouteImport } from './routes/_authed/sponsorships/create'
import { Route as AuthedProductsCreateRouteImport } from './routes/_authed/products/create'
import { Route as AuthedPaymentsCreateRouteImport } from './routes/_authed/payments/create'
import { Route as AuthedOrdersCreateRouteImport } from './routes/_authed/orders/create'
import { Route as AuthedContactsCreateRouteImport } from './routes/_authed/contacts/create'
import { Route as AuthedAnimalsTurnoutJournalRouteImport } from './routes/_authed/animals/turnout-journal'
import { Route as AuthedAnimalsTreatmentsJournalRouteImport } from './routes/_authed/animals/treatments-journal'
import { Route as AuthedAnimalsEarTagsRouteImport } from './routes/_authed/animals/ear-tags'
import { Route as AuthedAnimalsCreateRouteImport } from './routes/_authed/animals/create'
import { Route as AuthedSponsorshipsProgramsIndexRouteImport } from './routes/_authed/sponsorships/programs/index'
import { Route as AuthedSponsorshipsSponsorshipIdIndexRouteImport } from './routes/_authed/sponsorships/$sponsorshipId.index'
import { Route as AuthedProductsProductIdIndexRouteImport } from './routes/_authed/products/$productId.index'
import { Route as AuthedPaymentsPaymentIdIndexRouteImport } from './routes/_authed/payments/$paymentId.index'
import { Route as AuthedOrdersOrderIdIndexRouteImport } from './routes/_authed/orders/$orderId.index'
import { Route as AuthedContactsContactIdIndexRouteImport } from './routes/_authed/contacts/$contactId.index'
import { Route as AuthedAnimalsAnimalIdIndexRouteImport } from './routes/_authed/animals/$animalId.index'
import { Route as AuthedSponsorshipsProgramsCreateRouteImport } from './routes/_authed/sponsorships/programs/create'
import { Route as AuthedSponsorshipsSponsorshipIdEditRouteImport } from './routes/_authed/sponsorships/$sponsorshipId.edit'
import { Route as AuthedProductsProductIdEditRouteImport } from './routes/_authed/products/$productId.edit'
import { Route as AuthedPaymentsPaymentIdEditRouteImport } from './routes/_authed/payments/$paymentId.edit'
import { Route as AuthedOrdersOrderIdEditRouteImport } from './routes/_authed/orders/$orderId.edit'
import { Route as AuthedContactsContactIdEditRouteImport } from './routes/_authed/contacts/$contactId.edit'
import { Route as AuthedAnimalsAnimalIdEditRouteImport } from './routes/_authed/animals/$animalId.edit'
import { Route as AuthedSponsorshipsProgramsProgramIdIndexRouteImport } from './routes/_authed/sponsorships/programs/$programId.index'
import { Route as AuthedSponsorshipsProgramsProgramIdEditRouteImport } from './routes/_authed/sponsorships/programs/$programId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSponsorshipsIndexRoute = AuthedSponsorshipsIndexRouteImport.update({
  id: '/sponsorships/',
  path: '/sponsorships/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPaymentsIndexRoute = AuthedPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedContactsIndexRoute = AuthedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnimalsIndexRoute = AuthedAnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSponsorshipsCreateRoute =
  AuthedSponsorshipsCreateRouteImport.update({
    id: '/sponsorships/create',
    path: '/sponsorships/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsCreateRoute = AuthedProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPaymentsCreateRoute = AuthedPaymentsCreateRouteImport.update({
  id: '/payments/create',
  path: '/payments/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersCreateRoute = AuthedOrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedContactsCreateRoute = AuthedContactsCreateRouteImport.update({
  id: '/contacts/create',
  path: '/contacts/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnimalsTurnoutJournalRoute =
  AuthedAnimalsTurnoutJournalRouteImport.update({
    id: '/animals/turnout-journal',
    path: '/animals/turnout-journal',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsTreatmentsJournalRoute =
  AuthedAnimalsTreatmentsJournalRouteImport.update({
    id: '/animals/treatments-journal',
    path: '/animals/treatments-journal',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsEarTagsRoute = AuthedAnimalsEarTagsRouteImport.update({
  id: '/animals/ear-tags',
  path: '/animals/ear-tags',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnimalsCreateRoute = AuthedAnimalsCreateRouteImport.update({
  id: '/animals/create',
  path: '/animals/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSponsorshipsProgramsIndexRoute =
  AuthedSponsorshipsProgramsIndexRouteImport.update({
    id: '/sponsorships/programs/',
    path: '/sponsorships/programs/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsSponsorshipIdIndexRoute =
  AuthedSponsorshipsSponsorshipIdIndexRouteImport.update({
    id: '/sponsorships/$sponsorshipId/',
    path: '/sponsorships/$sponsorshipId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsProductIdIndexRoute =
  AuthedProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedPaymentsPaymentIdIndexRoute =
  AuthedPaymentsPaymentIdIndexRouteImport.update({
    id: '/payments/$paymentId/',
    path: '/payments/$paymentId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOrdersOrderIdIndexRoute =
  AuthedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedContactsContactIdIndexRoute =
  AuthedContactsContactIdIndexRouteImport.update({
    id: '/contacts/$contactId/',
    path: '/contacts/$contactId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsAnimalIdIndexRoute =
  AuthedAnimalsAnimalIdIndexRouteImport.update({
    id: '/animals/$animalId/',
    path: '/animals/$animalId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsProgramsCreateRoute =
  AuthedSponsorshipsProgramsCreateRouteImport.update({
    id: '/sponsorships/programs/create',
    path: '/sponsorships/programs/create',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsSponsorshipIdEditRoute =
  AuthedSponsorshipsSponsorshipIdEditRouteImport.update({
    id: '/sponsorships/$sponsorshipId/edit',
    path: '/sponsorships/$sponsorshipId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsProductIdEditRoute =
  AuthedProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedPaymentsPaymentIdEditRoute =
  AuthedPaymentsPaymentIdEditRouteImport.update({
    id: '/payments/$paymentId/edit',
    path: '/payments/$paymentId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOrdersOrderIdEditRoute = AuthedOrdersOrderIdEditRouteImport.update({
  id: '/orders/$orderId/edit',
  path: '/orders/$orderId/edit',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedContactsContactIdEditRoute =
  AuthedContactsContactIdEditRouteImport.update({
    id: '/contacts/$contactId/edit',
    path: '/contacts/$contactId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedAnimalsAnimalIdEditRoute =
  AuthedAnimalsAnimalIdEditRouteImport.update({
    id: '/animals/$animalId/edit',
    path: '/animals/$animalId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsProgramsProgramIdIndexRoute =
  AuthedSponsorshipsProgramsProgramIdIndexRouteImport.update({
    id: '/sponsorships/programs/$programId/',
    path: '/sponsorships/programs/$programId/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSponsorshipsProgramsProgramIdEditRoute =
  AuthedSponsorshipsProgramsProgramIdEditRouteImport.update({
    id: '/sponsorships/programs/$programId/edit',
    path: '/sponsorships/programs/$programId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/animals/create': typeof AuthedAnimalsCreateRoute
  '/animals/ear-tags': typeof AuthedAnimalsEarTagsRoute
  '/animals/treatments-journal': typeof AuthedAnimalsTreatmentsJournalRoute
  '/animals/turnout-journal': typeof AuthedAnimalsTurnoutJournalRoute
  '/contacts/create': typeof AuthedContactsCreateRoute
  '/orders/create': typeof AuthedOrdersCreateRoute
  '/payments/create': typeof AuthedPaymentsCreateRoute
  '/products/create': typeof AuthedProductsCreateRoute
  '/sponsorships/create': typeof AuthedSponsorshipsCreateRoute
  '/animals/': typeof AuthedAnimalsIndexRoute
  '/contacts/': typeof AuthedContactsIndexRoute
  '/orders/': typeof AuthedOrdersIndexRoute
  '/payments/': typeof AuthedPaymentsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/sponsorships/': typeof AuthedSponsorshipsIndexRoute
  '/animals/$animalId/edit': typeof AuthedAnimalsAnimalIdEditRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/orders/$orderId/edit': typeof AuthedOrdersOrderIdEditRoute
  '/payments/$paymentId/edit': typeof AuthedPaymentsPaymentIdEditRoute
  '/products/$productId/edit': typeof AuthedProductsProductIdEditRoute
  '/sponsorships/$sponsorshipId/edit': typeof AuthedSponsorshipsSponsorshipIdEditRoute
  '/sponsorships/programs/create': typeof AuthedSponsorshipsProgramsCreateRoute
  '/animals/$animalId/': typeof AuthedAnimalsAnimalIdIndexRoute
  '/contacts/$contactId/': typeof AuthedContactsContactIdIndexRoute
  '/orders/$orderId/': typeof AuthedOrdersOrderIdIndexRoute
  '/payments/$paymentId/': typeof AuthedPaymentsPaymentIdIndexRoute
  '/products/$productId/': typeof AuthedProductsProductIdIndexRoute
  '/sponsorships/$sponsorshipId/': typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  '/sponsorships/programs/': typeof AuthedSponsorshipsProgramsIndexRoute
  '/sponsorships/programs/$programId/edit': typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  '/sponsorships/programs/$programId/': typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/animals/create': typeof AuthedAnimalsCreateRoute
  '/animals/ear-tags': typeof AuthedAnimalsEarTagsRoute
  '/animals/treatments-journal': typeof AuthedAnimalsTreatmentsJournalRoute
  '/animals/turnout-journal': typeof AuthedAnimalsTurnoutJournalRoute
  '/contacts/create': typeof AuthedContactsCreateRoute
  '/orders/create': typeof AuthedOrdersCreateRoute
  '/payments/create': typeof AuthedPaymentsCreateRoute
  '/products/create': typeof AuthedProductsCreateRoute
  '/sponsorships/create': typeof AuthedSponsorshipsCreateRoute
  '/animals': typeof AuthedAnimalsIndexRoute
  '/contacts': typeof AuthedContactsIndexRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/payments': typeof AuthedPaymentsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/sponsorships': typeof AuthedSponsorshipsIndexRoute
  '/animals/$animalId/edit': typeof AuthedAnimalsAnimalIdEditRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/orders/$orderId/edit': typeof AuthedOrdersOrderIdEditRoute
  '/payments/$paymentId/edit': typeof AuthedPaymentsPaymentIdEditRoute
  '/products/$productId/edit': typeof AuthedProductsProductIdEditRoute
  '/sponsorships/$sponsorshipId/edit': typeof AuthedSponsorshipsSponsorshipIdEditRoute
  '/sponsorships/programs/create': typeof AuthedSponsorshipsProgramsCreateRoute
  '/animals/$animalId': typeof AuthedAnimalsAnimalIdIndexRoute
  '/contacts/$contactId': typeof AuthedContactsContactIdIndexRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdIndexRoute
  '/payments/$paymentId': typeof AuthedPaymentsPaymentIdIndexRoute
  '/products/$productId': typeof AuthedProductsProductIdIndexRoute
  '/sponsorships/$sponsorshipId': typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  '/sponsorships/programs': typeof AuthedSponsorshipsProgramsIndexRoute
  '/sponsorships/programs/$programId/edit': typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  '/sponsorships/programs/$programId': typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/animals/create': typeof AuthedAnimalsCreateRoute
  '/_authed/animals/ear-tags': typeof AuthedAnimalsEarTagsRoute
  '/_authed/animals/treatments-journal': typeof AuthedAnimalsTreatmentsJournalRoute
  '/_authed/animals/turnout-journal': typeof AuthedAnimalsTurnoutJournalRoute
  '/_authed/contacts/create': typeof AuthedContactsCreateRoute
  '/_authed/orders/create': typeof AuthedOrdersCreateRoute
  '/_authed/payments/create': typeof AuthedPaymentsCreateRoute
  '/_authed/products/create': typeof AuthedProductsCreateRoute
  '/_authed/sponsorships/create': typeof AuthedSponsorshipsCreateRoute
  '/_authed/animals/': typeof AuthedAnimalsIndexRoute
  '/_authed/contacts/': typeof AuthedContactsIndexRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/payments/': typeof AuthedPaymentsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/sponsorships/': typeof AuthedSponsorshipsIndexRoute
  '/_authed/animals/$animalId/edit': typeof AuthedAnimalsAnimalIdEditRoute
  '/_authed/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
  '/_authed/orders/$orderId/edit': typeof AuthedOrdersOrderIdEditRoute
  '/_authed/payments/$paymentId/edit': typeof AuthedPaymentsPaymentIdEditRoute
  '/_authed/products/$productId/edit': typeof AuthedProductsProductIdEditRoute
  '/_authed/sponsorships/$sponsorshipId/edit': typeof AuthedSponsorshipsSponsorshipIdEditRoute
  '/_authed/sponsorships/programs/create': typeof AuthedSponsorshipsProgramsCreateRoute
  '/_authed/animals/$animalId/': typeof AuthedAnimalsAnimalIdIndexRoute
  '/_authed/contacts/$contactId/': typeof AuthedContactsContactIdIndexRoute
  '/_authed/orders/$orderId/': typeof AuthedOrdersOrderIdIndexRoute
  '/_authed/payments/$paymentId/': typeof AuthedPaymentsPaymentIdIndexRoute
  '/_authed/products/$productId/': typeof AuthedProductsProductIdIndexRoute
  '/_authed/sponsorships/$sponsorshipId/': typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  '/_authed/sponsorships/programs/': typeof AuthedSponsorshipsProgramsIndexRoute
  '/_authed/sponsorships/programs/$programId/edit': typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  '/_authed/sponsorships/programs/$programId/': typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/animals/create'
    | '/animals/ear-tags'
    | '/animals/treatments-journal'
    | '/animals/turnout-journal'
    | '/contacts/create'
    | '/orders/create'
    | '/payments/create'
    | '/products/create'
    | '/sponsorships/create'
    | '/animals/'
    | '/contacts/'
    | '/orders/'
    | '/payments/'
    | '/products/'
    | '/sponsorships/'
    | '/animals/$animalId/edit'
    | '/contacts/$contactId/edit'
    | '/orders/$orderId/edit'
    | '/payments/$paymentId/edit'
    | '/products/$productId/edit'
    | '/sponsorships/$sponsorshipId/edit'
    | '/sponsorships/programs/create'
    | '/animals/$animalId/'
    | '/contacts/$contactId/'
    | '/orders/$orderId/'
    | '/payments/$paymentId/'
    | '/products/$productId/'
    | '/sponsorships/$sponsorshipId/'
    | '/sponsorships/programs/'
    | '/sponsorships/programs/$programId/edit'
    | '/sponsorships/programs/$programId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/'
    | '/animals/create'
    | '/animals/ear-tags'
    | '/animals/treatments-journal'
    | '/animals/turnout-journal'
    | '/contacts/create'
    | '/orders/create'
    | '/payments/create'
    | '/products/create'
    | '/sponsorships/create'
    | '/animals'
    | '/contacts'
    | '/orders'
    | '/payments'
    | '/products'
    | '/sponsorships'
    | '/animals/$animalId/edit'
    | '/contacts/$contactId/edit'
    | '/orders/$orderId/edit'
    | '/payments/$paymentId/edit'
    | '/products/$productId/edit'
    | '/sponsorships/$sponsorshipId/edit'
    | '/sponsorships/programs/create'
    | '/animals/$animalId'
    | '/contacts/$contactId'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/products/$productId'
    | '/sponsorships/$sponsorshipId'
    | '/sponsorships/programs'
    | '/sponsorships/programs/$programId/edit'
    | '/sponsorships/programs/$programId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/animals/create'
    | '/_authed/animals/ear-tags'
    | '/_authed/animals/treatments-journal'
    | '/_authed/animals/turnout-journal'
    | '/_authed/contacts/create'
    | '/_authed/orders/create'
    | '/_authed/payments/create'
    | '/_authed/products/create'
    | '/_authed/sponsorships/create'
    | '/_authed/animals/'
    | '/_authed/contacts/'
    | '/_authed/orders/'
    | '/_authed/payments/'
    | '/_authed/products/'
    | '/_authed/sponsorships/'
    | '/_authed/animals/$animalId/edit'
    | '/_authed/contacts/$contactId/edit'
    | '/_authed/orders/$orderId/edit'
    | '/_authed/payments/$paymentId/edit'
    | '/_authed/products/$productId/edit'
    | '/_authed/sponsorships/$sponsorshipId/edit'
    | '/_authed/sponsorships/programs/create'
    | '/_authed/animals/$animalId/'
    | '/_authed/contacts/$contactId/'
    | '/_authed/orders/$orderId/'
    | '/_authed/payments/$paymentId/'
    | '/_authed/products/$productId/'
    | '/_authed/sponsorships/$sponsorshipId/'
    | '/_authed/sponsorships/programs/'
    | '/_authed/sponsorships/programs/$programId/edit'
    | '/_authed/sponsorships/programs/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/': {
      id: '/_authed/sponsorships/'
      path: '/sponsorships'
      fullPath: '/sponsorships/'
      preLoaderRoute: typeof AuthedSponsorshipsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/': {
      id: '/_authed/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthedPaymentsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/': {
      id: '/_authed/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthedContactsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/': {
      id: '/_authed/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AuthedAnimalsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/create': {
      id: '/_authed/sponsorships/create'
      path: '/sponsorships/create'
      fullPath: '/sponsorships/create'
      preLoaderRoute: typeof AuthedSponsorshipsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/create': {
      id: '/_authed/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof AuthedProductsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/create': {
      id: '/_authed/payments/create'
      path: '/payments/create'
      fullPath: '/payments/create'
      preLoaderRoute: typeof AuthedPaymentsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/create': {
      id: '/_authed/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof AuthedOrdersCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/create': {
      id: '/_authed/contacts/create'
      path: '/contacts/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof AuthedContactsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/turnout-journal': {
      id: '/_authed/animals/turnout-journal'
      path: '/animals/turnout-journal'
      fullPath: '/animals/turnout-journal'
      preLoaderRoute: typeof AuthedAnimalsTurnoutJournalRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/treatments-journal': {
      id: '/_authed/animals/treatments-journal'
      path: '/animals/treatments-journal'
      fullPath: '/animals/treatments-journal'
      preLoaderRoute: typeof AuthedAnimalsTreatmentsJournalRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/ear-tags': {
      id: '/_authed/animals/ear-tags'
      path: '/animals/ear-tags'
      fullPath: '/animals/ear-tags'
      preLoaderRoute: typeof AuthedAnimalsEarTagsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/create': {
      id: '/_authed/animals/create'
      path: '/animals/create'
      fullPath: '/animals/create'
      preLoaderRoute: typeof AuthedAnimalsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/': {
      id: '/_authed/sponsorships/programs/'
      path: '/sponsorships/programs'
      fullPath: '/sponsorships/programs/'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/$sponsorshipId/': {
      id: '/_authed/sponsorships/$sponsorshipId/'
      path: '/sponsorships/$sponsorshipId'
      fullPath: '/sponsorships/$sponsorshipId/'
      preLoaderRoute: typeof AuthedSponsorshipsSponsorshipIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$productId/': {
      id: '/_authed/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof AuthedProductsProductIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/$paymentId/': {
      id: '/_authed/payments/$paymentId/'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId/'
      preLoaderRoute: typeof AuthedPaymentsPaymentIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/$orderId/': {
      id: '/_authed/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof AuthedOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/$contactId/': {
      id: '/_authed/contacts/$contactId/'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId/'
      preLoaderRoute: typeof AuthedContactsContactIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/$animalId/': {
      id: '/_authed/animals/$animalId/'
      path: '/animals/$animalId'
      fullPath: '/animals/$animalId/'
      preLoaderRoute: typeof AuthedAnimalsAnimalIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/create': {
      id: '/_authed/sponsorships/programs/create'
      path: '/sponsorships/programs/create'
      fullPath: '/sponsorships/programs/create'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/$sponsorshipId/edit': {
      id: '/_authed/sponsorships/$sponsorshipId/edit'
      path: '/sponsorships/$sponsorshipId/edit'
      fullPath: '/sponsorships/$sponsorshipId/edit'
      preLoaderRoute: typeof AuthedSponsorshipsSponsorshipIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$productId/edit': {
      id: '/_authed/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AuthedProductsProductIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payments/$paymentId/edit': {
      id: '/_authed/payments/$paymentId/edit'
      path: '/payments/$paymentId/edit'
      fullPath: '/payments/$paymentId/edit'
      preLoaderRoute: typeof AuthedPaymentsPaymentIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/$orderId/edit': {
      id: '/_authed/orders/$orderId/edit'
      path: '/orders/$orderId/edit'
      fullPath: '/orders/$orderId/edit'
      preLoaderRoute: typeof AuthedOrdersOrderIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/contacts/$contactId/edit': {
      id: '/_authed/contacts/$contactId/edit'
      path: '/contacts/$contactId/edit'
      fullPath: '/contacts/$contactId/edit'
      preLoaderRoute: typeof AuthedContactsContactIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/animals/$animalId/edit': {
      id: '/_authed/animals/$animalId/edit'
      path: '/animals/$animalId/edit'
      fullPath: '/animals/$animalId/edit'
      preLoaderRoute: typeof AuthedAnimalsAnimalIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/$programId/': {
      id: '/_authed/sponsorships/programs/$programId/'
      path: '/sponsorships/programs/$programId'
      fullPath: '/sponsorships/programs/$programId/'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsProgramIdIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sponsorships/programs/$programId/edit': {
      id: '/_authed/sponsorships/programs/$programId/edit'
      path: '/sponsorships/programs/$programId/edit'
      fullPath: '/sponsorships/programs/$programId/edit'
      preLoaderRoute: typeof AuthedSponsorshipsProgramsProgramIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAnimalsCreateRoute: typeof AuthedAnimalsCreateRoute
  AuthedAnimalsEarTagsRoute: typeof AuthedAnimalsEarTagsRoute
  AuthedAnimalsTreatmentsJournalRoute: typeof AuthedAnimalsTreatmentsJournalRoute
  AuthedAnimalsTurnoutJournalRoute: typeof AuthedAnimalsTurnoutJournalRoute
  AuthedContactsCreateRoute: typeof AuthedContactsCreateRoute
  AuthedOrdersCreateRoute: typeof AuthedOrdersCreateRoute
  AuthedPaymentsCreateRoute: typeof AuthedPaymentsCreateRoute
  AuthedProductsCreateRoute: typeof AuthedProductsCreateRoute
  AuthedSponsorshipsCreateRoute: typeof AuthedSponsorshipsCreateRoute
  AuthedAnimalsIndexRoute: typeof AuthedAnimalsIndexRoute
  AuthedContactsIndexRoute: typeof AuthedContactsIndexRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedPaymentsIndexRoute: typeof AuthedPaymentsIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedSponsorshipsIndexRoute: typeof AuthedSponsorshipsIndexRoute
  AuthedAnimalsAnimalIdEditRoute: typeof AuthedAnimalsAnimalIdEditRoute
  AuthedContactsContactIdEditRoute: typeof AuthedContactsContactIdEditRoute
  AuthedOrdersOrderIdEditRoute: typeof AuthedOrdersOrderIdEditRoute
  AuthedPaymentsPaymentIdEditRoute: typeof AuthedPaymentsPaymentIdEditRoute
  AuthedProductsProductIdEditRoute: typeof AuthedProductsProductIdEditRoute
  AuthedSponsorshipsSponsorshipIdEditRoute: typeof AuthedSponsorshipsSponsorshipIdEditRoute
  AuthedSponsorshipsProgramsCreateRoute: typeof AuthedSponsorshipsProgramsCreateRoute
  AuthedAnimalsAnimalIdIndexRoute: typeof AuthedAnimalsAnimalIdIndexRoute
  AuthedContactsContactIdIndexRoute: typeof AuthedContactsContactIdIndexRoute
  AuthedOrdersOrderIdIndexRoute: typeof AuthedOrdersOrderIdIndexRoute
  AuthedPaymentsPaymentIdIndexRoute: typeof AuthedPaymentsPaymentIdIndexRoute
  AuthedProductsProductIdIndexRoute: typeof AuthedProductsProductIdIndexRoute
  AuthedSponsorshipsSponsorshipIdIndexRoute: typeof AuthedSponsorshipsSponsorshipIdIndexRoute
  AuthedSponsorshipsProgramsIndexRoute: typeof AuthedSponsorshipsProgramsIndexRoute
  AuthedSponsorshipsProgramsProgramIdEditRoute: typeof AuthedSponsorshipsProgramsProgramIdEditRoute
  AuthedSponsorshipsProgramsProgramIdIndexRoute: typeof AuthedSponsorshipsProgramsProgramIdIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAnimalsCreateRoute: AuthedAnimalsCreateRoute,
  AuthedAnimalsEarTagsRoute: AuthedAnimalsEarTagsRoute,
  AuthedAnimalsTreatmentsJournalRoute: AuthedAnimalsTreatmentsJournalRoute,
  AuthedAnimalsTurnoutJournalRoute: AuthedAnimalsTurnoutJournalRoute,
  AuthedContactsCreateRoute: AuthedContactsCreateRoute,
  AuthedOrdersCreateRoute: AuthedOrdersCreateRoute,
  AuthedPaymentsCreateRoute: AuthedPaymentsCreateRoute,
  AuthedProductsCreateRoute: AuthedProductsCreateRoute,
  AuthedSponsorshipsCreateRoute: AuthedSponsorshipsCreateRoute,
  AuthedAnimalsIndexRoute: AuthedAnimalsIndexRoute,
  AuthedContactsIndexRoute: AuthedContactsIndexRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedPaymentsIndexRoute: AuthedPaymentsIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedSponsorshipsIndexRoute: AuthedSponsorshipsIndexRoute,
  AuthedAnimalsAnimalIdEditRoute: AuthedAnimalsAnimalIdEditRoute,
  AuthedContactsContactIdEditRoute: AuthedContactsContactIdEditRoute,
  AuthedOrdersOrderIdEditRoute: AuthedOrdersOrderIdEditRoute,
  AuthedPaymentsPaymentIdEditRoute: AuthedPaymentsPaymentIdEditRoute,
  AuthedProductsProductIdEditRoute: AuthedProductsProductIdEditRoute,
  AuthedSponsorshipsSponsorshipIdEditRoute:
    AuthedSponsorshipsSponsorshipIdEditRoute,
  AuthedSponsorshipsProgramsCreateRoute: AuthedSponsorshipsProgramsCreateRoute,
  AuthedAnimalsAnimalIdIndexRoute: AuthedAnimalsAnimalIdIndexRoute,
  AuthedContactsContactIdIndexRoute: AuthedContactsContactIdIndexRoute,
  AuthedOrdersOrderIdIndexRoute: AuthedOrdersOrderIdIndexRoute,
  AuthedPaymentsPaymentIdIndexRoute: AuthedPaymentsPaymentIdIndexRoute,
  AuthedProductsProductIdIndexRoute: AuthedProductsProductIdIndexRoute,
  AuthedSponsorshipsSponsorshipIdIndexRoute:
    AuthedSponsorshipsSponsorshipIdIndexRoute,
  AuthedSponsorshipsProgramsIndexRoute: AuthedSponsorshipsProgramsIndexRoute,
  AuthedSponsorshipsProgramsProgramIdEditRoute:
    AuthedSponsorshipsProgramsProgramIdEditRoute,
  AuthedSponsorshipsProgramsProgramIdIndexRoute:
    AuthedSponsorshipsProgramsProgramIdIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
